class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'ar': {
      'where_to': 'إلى أين؟',
      'search_hint': 'ابحث عن مكان، شارع، مدينة...',
      'home': 'المنزل',
      'work': 'العمل',
      'new_place': 'جديد',
      'recent': 'السابقة',
      'start_navigation': 'ابدأ الملاحة الآن',
      'route_to': 'المسار إلى',
      'fuel_stations': 'محطات الوقود والأسعار',
      'places': 'الأماكن والخدمات',
      'profile': 'حسابي والسمعة',
      'map': 'الخريطة',
      'report_hazard': 'إبلاغ عن خطر على الطريق',
      'sos': 'نداء طوارئ',
      'recenter': 'موقعي',
      'eta': 'الوصول',
      'distance': 'المسافة',
      'duration': 'الوقت',
      'fastest_route': 'المسار الأسرع',
      'alternative_route': 'مسار بديل',
      'reputation_score': 'نقاط السمعة',
      'confirmed_reports': 'البلاغات المؤكدة',
      'helpful_answers': 'إجابات مفيدة',
      'new_driver': 'سائق جديد',
      'no_badges': 'لا توجد أوسمة بعد',
      'no_vehicles': 'لا توجد مركبات مضافة',
      'settings': 'الإعدادات والخصوصية',
      'app_language': 'لغة التطبيق',
      'voice_guidance': 'التوجيه الصوتي أثناء القيادة',
      'accident': 'حادث سير',
      'radar': 'رادار سرعة',
      'traffic': 'ازدحام مروري',
      'road_closed': 'إغلاق طريق',
      'hazard': 'خطر / عائق',
      'police': 'سيطرة أمنية',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد البلاغ',
      'end_trip': 'إنهاء الرحلة',
      'arrived': 'لقد وصلت إلى وجهتك!',
      'erbil_citadel': 'قلعة أربيل',
      'street_40': 'شارع 40',
      'rizgary_hospital': 'مستشفى رزكاري',
      'family_mall': 'فاميلي مول',
      'erbil_airport': 'مطار أربيل الدولي',
      'dream_city': 'مجمع دريم سيتي',
      'shaqlawa': 'شقلاوة',
    },
    'ku': {
      'where_to': 'بۆ کوێ؟',
      'search_hint': 'بگەڕێ بۆ شوێن، شەقام، شار...',
      'home': 'ماڵەوە',
      'work': 'کار',
      'new_place': 'نوێ',
      'recent': 'پێشوو',
      'start_navigation': 'دەستپێکردنی ڕێڕەو',
      'route_to': 'ڕێگا بەرەو',
      'fuel_stations': 'بنزینخانەکان و نرخەکان',
      'places': 'شوێنەکان و خزمەتگوزارییەکان',
      'profile': 'هەژمارەکەم و ناوبانگ',
      'map': 'نەخشە',
      'report_hazard': 'ڕاگەیاندنی مەترسی لەسەر ڕێگا',
      'sos': 'فریاکەوتنی بەپەلە',
      'recenter': 'شوێنی من',
      'eta': 'گەیشتن',
      'distance': 'دووری',
      'duration': 'کات',
      'fastest_route': 'خێراترین ڕێگا',
      'alternative_route': 'ڕێگای جێگرەوە',
      'reputation_score': 'خاڵەکانی ناوبانگ',
      'confirmed_reports': 'ڕاپۆرتە پەسەندکراوەکان',
      'helpful_answers': 'وەڵامە بەسوودەکان',
      'new_driver': 'شۆفێری نوێ',
      'no_badges': 'هێشتا هیچ نیشانەیەک نییە',
      'no_vehicles': 'هیچ ئۆتۆمبێلێک زیاد نەکراوە',
      'settings': 'ڕێکخستنەکان و تایبەتمەندی',
      'app_language': 'زمانی ئەپڵیکەیشن',
      'voice_guidance': 'ڕێنمایی دەنگی لە کاتی لێخوڕیندا',
      'accident': 'ڕووداوی هاتوچۆ',
      'radar': 'ڕاداری خێرایی',
      'traffic': 'قەرەباڵغی هاتوچۆ',
      'road_closed': 'ڕێگا داخراوە',
      'hazard': 'مەترسی / بەربەست',
      'police': 'خاڵی پشکنین',
      'cancel': 'پاشگەزبوونەوە',
      'confirm': 'پەسەندکردنی ڕاپۆرت',
      'end_trip': 'کۆتایی گەشت',
      'arrived': 'گەیشتیتە جێگای مەبەست!',
      'erbil_citadel': 'قەڵای هەولێر',
      'street_40': 'شەقامی 40 مەتری',
      'rizgary_hospital': 'نەخۆشخانەی ڕزگاری',
      'family_mall': 'فامیلی مۆڵ',
      'erbil_airport': 'فڕۆکەخانەی نێودەوڵەتی هەولێر',
      'dream_city': 'دریم سیتی',
      'shaqlawa': 'شەقڵاوە',
    },
    'en': {
      'where_to': 'Where to?',
      'search_hint': 'Search for place, street, city...',
      'home': 'Home',
      'work': 'Work',
      'new_place': 'New',
      'recent': 'Recent',
      'start_navigation': 'Start Drive',
      'route_to': 'Route to',
      'fuel_stations': 'Fuel Stations & Prices',
      'places': 'Places & Services',
      'profile': 'My Profile & Trust',
      'map': 'Map',
      'report_hazard': 'Report Road Hazard',
      'sos': 'SOS / Road Assist',
      'recenter': 'My Location',
      'eta': 'ETA',
      'distance': 'Distance',
      'duration': 'Duration',
      'fastest_route': 'Fastest Route',
      'alternative_route': 'Alternative Route',
      'reputation_score': 'Reputation Score',
      'confirmed_reports': 'Confirmed Reports',
      'helpful_answers': 'Helpful Answers',
      'new_driver': 'New Driver',
      'no_badges': 'No badges yet',
      'no_vehicles': 'No vehicles added',
      'settings': 'Settings & Privacy',
      'app_language': 'App Language',
      'voice_guidance': 'Voice Guidance while driving',
      'accident': 'Car Crash',
      'radar': 'Speed Radar',
      'traffic': 'Traffic Jam',
      'road_closed': 'Road Closed',
      'hazard': 'Road Hazard',
      'police': 'Police Checkpoint',
      'cancel': 'Cancel',
      'confirm': 'Submit Report',
      'end_trip': 'End Trip',
      'arrived': 'You have arrived!',
      'erbil_citadel': 'Erbil Citadel',
      'street_40': '40m Street',
      'rizgary_hospital': 'Rizgary Hospital',
      'family_mall': 'Family Mall',
      'erbil_airport': 'Erbil Intl Airport',
      'dream_city': 'Dream City',
      'shaqlawa': 'Shaqlawa',
    },
  };

  static String tr(String key, String lang) {
    return _values[lang]?[key] ?? _values['ar']?[key] ?? key;
  }
}
